#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Jonathan Reem <jonathan.reem@gmail.com>
#

# Has to be loaded before prezto or hub completion is not loaded.
alias git="hub"

# Completion
fpath=('/usr/local/share/zsh/site-functions/' $fpath)
fpath=(~/.zsh $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# All modules can be found in this directory.
#
# To go there, simply type `modules` in your shell.
#
# Anything with the `.zsh` extension placed in this directory or
# any child directories will automatically be sourced on startup.
alias modules="${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshmodules"

# Source vars first, so as to not break other things.
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/vars.zsh"

# Source all other modules.
for module in `find ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshmodules -type f -name *.zsh`; do
    source $module
done


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/reem/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/reem/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/reem/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/reem/google-cloud-sdk/completion.zsh.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
